export const GET_RATE_USD_UAH = 'GET_RATE_USD_UAH';
export const GET_RATE_EUR_UAH = 'GET_RATE_EUR_UAH';
export const GET_CURRENT_RATE = 'GET_CURRENT_RATE';
export const SET_CURRENCY_FROM = 'SET_CURRENCY_FROM';
export const SET_CURRENCY_TO = 'SET_CURRENCY_TO';
export const SET_AMOUNT = 'SET_AMOUNT';
export const SET_AMOUNT_FROM = 'SET_AMOUNT_FROM';
export const GET_CURRENCIES_LIST = 'GET_CURRENCIES_LIST';
